### ISSUE TITLE
Jumping on goombas while dead knocks out goomba but doesn't bounce player

### ISSUE THREAD

**Issue by alancnet** [novitas315/Trancend#3]
Jump on a goomba while dead, and it will get knocked out, but you won't bounce. 
Expected: Only interact with goomba while in the same state of dead or alive.

![image](https://cloud.githubusercontent.com/assets/2042102/8563918/4f51f8e4-2502-11e5-8fae-12b0e224d4af.png)

**Comment by novitas315** [comment]
Good point. I'll fix this.

**Comment by novitas315** [comment]
Fixed. http://www.mediafire.com/download/8gx4tuip5ufl6p7/Transcend.exe
